// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("faf90100-1477-49f6-8c08-b9f8c47bde3a")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("RandomAccessPerlinNoise.Tests")]
